#!/bin/bash

#let $# || { echo No arguments supplied; exit 1; }

GUSER="minero"
MINER="claymore.tgz"
TMP="temp"
cd $TMP
VPNCONF=$(ls *.conf)
cd ..
KERNELVER=$(ls /boot/ | grep vmlinuz)
KERNELVER=${KERNELVEL:8}

#install new kernel
#dpkg -i --force-confnew $TMP/*.deb

#remove installed kernel
#apt --purge remove -y linux-image-4.15* linux-headers-4.15* linux-modules-4.15*

#update repository
apt update

#install linux firmware for wifi
#apt install -y linux-firmware
apt install -y pv clinfo

#install and set spanish locale
apt install -y language-pack-es
update-locale LANG=es_VE.UTF-8 LC_ALL=es_VE.UTF-8 LANGUAGE
#set default keyboard to espanish
sed -i 's/us/es/g' /etc/default/keyboard
#set timezone
ln -sf /usr/share/zoneinfo/America/Caracas /etc/localtime
#set hostname
echo ${VPNCONF%%.*} >/etc/hostname

#create user
useradd -m $GUSER -s /bin/bash
usermod -aG sudo,video $GUSER
echo "$GUSER:$GUSER" | chpasswd

#reset openssh server configuration
apt purge openssh-server -y
apt install openssh-server -y

#install openvpn
apt install -y openvpn
cp $TMP/$VPNCONF /etc/openvpn

#remove cloud utils
rm -r /etc/cloud/
apt purge -y cloud* lxd* lxc* unattended-upgrades

#fix network driver
echo -e "network:\n  version: 2\n  renderer: NetworkManager\n" >>/etc/netplan/config.yaml
apt install -y network-manager r8168-dkms

#install gpu driver
#cd $TMP/$DRV
#./amdgpu-pro-install -y --compute
#cd ../..

#install desktop
#apt install -y xfce4 xfce4-session lightdm xubuntu-default-settings
#apt install -y wspanish language-pack-gnome-es gnome-user-docs-es mousepad

#install browser
#apt install -y firefox firefox-locale-es ffmpeg

#install claymore
cd /home/$GUSER
tar xzvf /$TMP/$MINER
./minero/claymore/install.sh
[ -f /$TMP/config.txt ] && cp /$TMP/config.txt minero/claymore/
cd /

#fix grub
rm /etc/default/grub.d/50-cloudimg-settings.cfg
#echo -e "\nGRUB_GFXPAYLOAD_LINUX=text\nGRUB_TERMINAL=console\n" >/etc/default/grub
[ -f /$TMP/disk.cfg ] && sudo fdisk ${DEV:0:-1} <$TMP/disk.cfg
grub-mkconfig
update-grub
grub-install ${DEV:0:-1}

